#!/usr/bin/env php
<?php

$_Tequila_dir = defined('__DIR__') ? __DIR__ : dirname(__FILE__);

if (!class_exists('Gallic'))
{
	require $_Tequila_dir.'/Gallic.php';
}
Gallic::$include_dirs[] = $_Tequila_dir;

unset($_Tequila_dir);

////////////////////////////////////////////////////////////////////////////////

function loadConfig(array $config, Tequila $tequila)
{
	foreach (array('prompt') as $entry)
	{
		if (isset($config[$entry]))
		{
			$tequila->$entry = $tequila->parseConfigEntry($config[$entry]);
		}
	}

	if (isset($config['include_dirs']))
	{
		$tequila->class_loader = new Tequila_ClassLoader_Gallic(
			$tequila->parseConfigEntry($config['include_dirs'])
		);
	}

	if (isset($config['log_file']))
	{
		$tequila->logger = new Tequila_Logger_File(
			$tequila->parseConfigEntry($config['log_file'])
		);
	}
}

////////////////////////////////////////////////////////////////////////////////

$tequila = Tequila::create();

loadConfig(parse_ini_file('/etc/tequila/config.ini'), $tequila);

$tequila->start();
