#!/usr/bin/env php
<?php
/**
 * @author Julien Fontanet <julien.fontanet@isonoe.net>
 */

$_Tequila_dir = defined('__DIR__') ? __DIR__ : dirname(__FILE__);

require($_Tequila_dir.'/lib/Gallic.php');

////////////////////////////////////////////////////////////////////////////////

function getConfig($ini_file, array $args = null)
{
	$config = array();

	if (isset($ini_file))
	{
		foreach (parse_ini_file($ini_file) as $key => $value)
		{
			// For compatibility.
			$key = str_replace('_', '-', $key);

			$config[$key] = $value;
		}
	}

	foreach ($args as $arg)
	{
		if (!preg_match('/^--([^=]+)(?:=(.*))?$/', $arg, $matches))
		{
			fwrite(STDERR, 'Incorrect option format: '.$arg);
			exit(1);
		}

		$key   = $matches[1];
		$value = isset($matches[2]) ? $matches[2] : true;

		if (substr_compare($key, '[]', -2) === 0)
		{
			$config[substr($key, 0, -2)][] = $value;
		}
		else
		{
			$config[$key] = $value;
		}
	}

	return $config;
}

////////////////////////////////////////////////////////////////////////////////

$config = getConfig(
	$_Tequila_dir.'/config.ini',
	array_slice($_SERVER['argv'], 1)
);

unset($_Tequila_dir);

$tequila = new Tequila(
	new Tequila_ClassLoader_Gallic(array())
);

foreach ($config as $key => $value)
{
	$tequila->setOption($key, $value);
}

$tequila->start();

/*
 * Local Variables:
 * mode: php
 * End:
 */
