#!/usr/bin/env php
<?php
/**
 * @author Julien Fontanet <julien.fontanet@isonoe.net>
 */

$_Tequila_dir = defined('__DIR__') ? __DIR__ : dirname(__FILE__);

set_include_path(implode(PATH_SEPARATOR, array(
	$_Tequila_dir.'/../libs/gallic/src',
	'/usr/share/php5/lib',
	'/usr/share/php',
)));

if (!class_exists('Gallic'))
{
	require 'Gallic.php';
}
Gallic::$include_dirs[] = $_Tequila_dir;

////////////////////////////////////////////////////////////////////////////////

function loadConfig(array $config, Tequila $tequila)
{
	// Plain Tequila attributes.
	foreach (array('prompt') as $entry)
	{
		if (isset($config[$entry]))
		{
			$tequila->$entry = $tequila->parseConfigEntry($config[$entry]);
		}
	}

	if (isset($config['include_dirs']))
	{
		$tequila->class_loader = new Tequila_ClassLoader_Gallic(
			$tequila->parseConfigEntry($config['include_dirs'])
		);
	}

	if (isset($config['log_file']))
	{
		$tequila->logger = new Tequila_Logger_File(
			$tequila->parseConfigEntry($config['log_file'])
		);
	}
}

////////////////////////////////////////////////////////////////////////////////

$tequila = new Tequila();

// First, tries to find the config file in the current directory.
if (is_file($_Tequila_dir.'/config.ini'))
{
	loadConfig(parse_ini_file($_Tequila_dir.'/config.ini'), $tequila);
}
else
{
	loadConfig(parse_ini_file('/etc/tequila/config.ini'), $tequila);
}

unset($_Tequila_dir);

$tequila->start();

/*
 * Local Variables:
 * mode: php
 * End:
 */
